// jsonData js
let json = `[{"id":1,"first_name":"Stearn","last_name":"Curreen","email":"scurreen0@dailymail.co.uk","gender":"Male","salary":6930},
{"id":2,"first_name":"Linc","last_name":"Klosser","email":"lklosser1@lulu.com","gender":"Male","salary":4063},
{"id":3,"first_name":"Tadio","last_name":"McGahy","email":"tmcgahy2@elegantthemes.com","gender":"Male","salary":3273},
{"id":4,"first_name":"Lorrin","last_name":"Vipan","email":"lvipan3@dot.gov","gender":"Female","salary":4704},
{"id":5,"first_name":"Casper","last_name":"Bonnavant","email":"cbonnavant4@comsenz.com","gender":"Male","salary":6425},
{"id":6,"first_name":"Larry","last_name":"Dermot","email":"ldermot5@a8.net","gender":"Male","salary":2742},
{"id":7,"first_name":"Joshuah","last_name":"Moyce","email":"jmoyce6@jigsy.com","gender":"Male","salary":3290},
{"id":8,"first_name":"Kari","last_name":"Drane","email":"kdrane7@trellian.com","gender":"Female","salary":7926},
{"id":9,"first_name":"Darla","last_name":"Butter","email":"dbutter8@economist.com","gender":"Female","salary":7995},
{"id":10,"first_name":"Filip","last_name":"Radborn","email":"fradborn9@jugem.jp","gender":"Non-binary","salary":5916},
{"id":11,"first_name":"Alexis","last_name":"Veart","email":"avearta@bluehost.com","gender":"Male","salary":3501},
{"id":12,"first_name":"Kyrstin","last_name":"Nouch","email":"knouchb@nyu.edu","gender":"Female","salary":4461},
{"id":13,"first_name":"Lester","last_name":"Beautyman","email":"lbeautymanc@youtu.be","gender":"Male","salary":2298},
{"id":14,"first_name":"Katerine","last_name":"Castelot","email":"kcastelotd@ucla.edu","gender":"Female","salary":5497},
{"id":15,"first_name":"Barnabas","last_name":"Pinchin","email":"bpinchine@nydailynews.com","gender":"Male","salary":3528},
{"id":16,"first_name":"Hastie","last_name":"Freebury","email":"hfreeburyf@xing.com","gender":"Male","salary":6481},
{"id":17,"first_name":"Angelita","last_name":"Milland","email":"amillandg@jalbum.net","gender":"Female","salary":2114},
{"id":18,"first_name":"Cyril","last_name":"Kroin","email":"ckroinh@biglobe.ne.jp","gender":"Male","salary":2506},
{"id":19,"first_name":"Christoph","last_name":"Dawdary","email":"cdawdaryi@chronoengine.com","gender":"Male","salary":2432},
{"id":20,"first_name":"Wayland","last_name":"Timperley","email":"wtimperleyj@about.com","gender":"Male","salary":2498}]`;